//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Data.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormPreExamine
    {
        public long ID { get; set; }
        public long FormMedicalID { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string Anamnesa { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Respiratory { get; set; }
        public Nullable<int> Pulse { get; set; }
        public Nullable<int> Systolic { get; set; }
        public Nullable<int> Diastolic { get; set; }
        public string Others { get; set; }
        public string RightEye { get; set; }
        public string LeftEye { get; set; }
        public string ColorBlind { get; set; }
        public Nullable<System.DateTime> MenstrualDate { get; set; }
        public Nullable<System.DateTime> KBDate { get; set; }
        public string DailyGlasses { get; set; }
        public string ExamineGlasses { get; set; }
        public Nullable<short> RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual FormMedical FormMedical { get; set; }
    }
}
