
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Klinik.Data.DataRepository
{

using System;
    using System.Collections.Generic;
    
public partial class MCUPackage
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MCUPackage()
    {

        this.Appointments = new HashSet<Appointment>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public Nullable<int> AgeStart { get; set; }

    public Nullable<int> AgeEnd { get; set; }

    public Nullable<int> GradeID { get; set; }

    public short RowStatus { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> NodifiedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Appointment> Appointments { get; set; }

}

}
