
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Klinik.Data.DataRepository
{

using System;
    using System.Collections.Generic;
    
public partial class PanggilanPoli
{

    public long Id { get; set; }

    public string QueueCode { get; set; }

    public string Status { get; set; }

    public int PoliID { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int SortNumber { get; set; }



    public virtual Poli Poli { get; set; }

}

}
