//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Data.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public int id { get; set; }
        public int PurchaseOrderId { get; set; }
        public int ProductId { get; set; }
        public string namabarang { get; set; }
        public double tot_pemakaian { get; set; }
        public double sisa_stok { get; set; }
        public double qty { get; set; }
        public Nullable<double> qty_add { get; set; }
        public string reason_add { get; set; }
        public double total { get; set; }
        public string nama_by_ho { get; set; }
        public Nullable<double> qty_by_ho { get; set; }
        public string remark_by_ho { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> statusop { get; set; }
        public Nullable<int> RowStatus { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
