
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Klinik.Data.DataRepository
{

using System;
    using System.Collections.Generic;
    
public partial class stok1
{

    public int id { get; set; }

    public int ProductId { get; set; }

    public long ClinicId { get; set; }

    public Nullable<double> stok_real { get; set; }

    public Nullable<double> stok_prev { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> RowStatus { get; set; }

    public Nullable<int> statusop { get; set; }



    public virtual Clinic Clinic { get; set; }

    public virtual Product Product { get; set; }

}

}
