
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Klinik.Data.DataRepository
{

using System;
    using System.Collections.Generic;
    
public partial class stok_bulanan
{

    public int ProductId { get; set; }

    public long ClinicId { get; set; }

    public System.DateTime thnbln { get; set; }

    public Nullable<double> stok { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> RowStatus { get; set; }

    public Nullable<int> statusop { get; set; }

}

}
