
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Klinik.Data.DataRepository
{

using System;
    using System.Collections.Generic;
    
public partial class SuratRujukanLabKeluar
{

    public long Id { get; set; }

    public string NoSurat { get; set; }

    public Nullable<long> FormMedicalID { get; set; }

    public string DokterPengirim { get; set; }

    public int LabItemId { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }



    public virtual LabItem LabItem { get; set; }

}

}
