//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Web.DataAccess.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePrivilege
    {
        public long ID { get; set; }
        public long RoleID { get; set; }
        public long PrivilegeID { get; set; }
        public Nullable<long> MenuId { get; set; }
    
        public virtual OrganizationRole OrganizationRole { get; set; }
        public virtual Privilege Privilege { get; set; }
    }
}
