//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public Nullable<long> ParentMenuId { get; set; }
        public string PageLink { get; set; }
        public int SortIndex { get; set; }
        public Nullable<bool> HasChild { get; set; }
        public Nullable<bool> IsMenu { get; set; }
    }
}
